# Generated by Django 5.2 on 2025-04-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Untitled Task', max_length=100),
        ),
    ]
